# 機器學習 - KNN近鄰演算法 (二)
- 學期: 111 人工智慧 Summer Session 教材 (師培中心)
- 杜主民

## KNN 案例二 (使用 sklearn 內建 iris 資料集)
- 分隔訓練資料和測試資料 (Train/Test split)
- 選擇 k=1

In [21]:
# 1) import 套件、模組、函數、設定繪圖
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [22]:
# 2) 讀取資料集 (sklearn 內建之  iris)
from sklearn.datasets import load_iris
iris = load_iris()

In [23]:
# 3) 選取 feature X 資料與 response Y 資料
X = iris.data
y = iris.target

In [24]:
# 4) 分隔訓練資料和測試資料
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=4)

In [25]:
print('X_train.shape:', X_train.shape)
print('y_train.shape:', y_train.shape)
print('X_test.shape:', X_test.shape)
print('y_test.shape:', y_test.shape)

X_train.shape: (90, 4)
y_train.shape: (90,)
X_test.shape: (60, 4)
y_test.shape: (60,)


- 建立物件 knn 物件 (或稱為 'estimator')
- 建立物件同時必須指定 'neighbor'的 k 值，也就是近鄰的數量

In [27]:
# 5) 代入資料建立 KNeighborsClassifier 模型
from sklearn.neighbors import KNeighborsClassifier

# 建立物件 knn 物件，指定 'neighbor' k 值為 1
knn = KNeighborsClassifier(n_neighbors=1)

# 代入訓練資料建立模型
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

### 建立模型 knn 後，開始進行預測

In [28]:
y_pred = knn.predict(X_test)

In [29]:
from sklearn import metrics
print('預測的正確率: ', metrics.accuracy_score(y_test, y_pred))

預測的正確率:  0.95


In [30]:
y_test

array([2, 0, 2, 2, 2, 1, 1, 0, 0, 2, 0, 0, 0, 1, 2, 0, 1, 0, 0, 2, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 2, 0, 1, 2, 2, 1, 1, 0, 2, 0, 1, 0,
       2, 0, 0, 1, 1, 2, 0, 1, 2, 2, 1, 1, 0, 1, 2, 1])

In [31]:
y_pred

array([2, 0, 2, 2, 2, 1, 2, 0, 0, 1, 0, 0, 0, 1, 2, 0, 1, 0, 0, 2, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 2, 0, 1, 2, 2, 1, 1, 0, 2, 0, 1, 0,
       2, 0, 0, 1, 1, 2, 0, 1, 2, 2, 1, 1, 0, 1, 1, 1])

In [32]:
# 6) 預測結果: y_pred
# 例如，有一朵新發現的 iris，這朵花的 sepal length, sepal width, petal length, petal width 分別是 [2, 6, 4, 3]，請問這朵應該是哪一類的 iris?
knn.predict([[2, 6, 4, 3]])

array([2])

PS: 代入 `predict()` 的測試資料，例如上面的 [2, 6, 4, 3]，必須是 2 維的資料型態

In [33]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

#### 答案是第 2 類，但第 2 到底為何類?
- 從 iris.target_names 可以看出 iris 的種類。
- 答案是 **virginica**。

In [34]:
## 一次預測 2 筆以上資料
X_new = [[5, 4, 3, 2], [3, 5, 4, 2], [5, 5, 2, 2]]
knn.predict(X_new)

array([1, 2, 0])

### 那麼，到底這個預測準確度為何?

In [35]:
y_pred = knn.predict(X_test)

In [36]:
from sklearn import metrics
print('預測的正確率: ', metrics.accuracy_score(y_test, y_pred))

預測的正確率:  0.95
